### ISSUE TITLE
C or C++ and coding style

### ISSUE THREAD

**Issue by Iey4iej3** [Neo-Desktop/WindowsXPKg#11]
It seems to me that the code, despite with extension `.cpp`, is in fact in C. For example,

``` C
#include <stdio.h>
```

is [deprecated](https://stackoverflow.com/a/7596439) in C++. The only exception is that, in C, the "correct" prototype of a function without parameter is, say, `int main(void)`. The prototype `(void)` instead of `()` is introduced in C for historic reasons.

It might also be better to improve the code according to latest standards. For example, the return type in https://github.com/Neo-Desktop/WindowsXPKg/blob/ac47a88f7e253fc86a06b1250f62d6938bd3ccb9/server_algorithm.cpp#L91 seems to be better to be `bool` (with `stdbool.h` included in C99). It might also be better to define variables `i,j,k` in the for-loop https://github.com/Neo-Desktop/WindowsXPKg/blob/ac47a88f7e253fc86a06b1250f62d6938bd3ccb9/server_algorithm.cpp#L98 instead (C99 and later).

**Comment by Neo-Desktop** [comment]
I think this is still a bit of a work in progress, but for now I think it's safe to call this completed
