### ISSUE TITLE
Cannot find OpenSSL

### ISSUE THREAD

**Issue by GlennSchner** [Neo-Desktop/WindowsXPKg#20]
After following install instructions, the following happens:
`CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindOpenSSL.cmake:574 (find_package_handle_standard_args)
  CMakeLists.txt:7 (FIND_PACKAGE)
`
OpenSSL is installed & so are all other dependencies, I think. I'm compiling this in the home folder if that matters any. Maybe this is related to #12 ?

**Comment by Neo-Desktop** [comment]
what distro are you compiling on and where are your openssl dev headers located?

**Comment by thepwrtank18** [comment]
Use OpenSSL 0.9.8, not the latest version (3.1.1).

**Comment by GlennSchner** [comment]
> Use OpenSSL 0.9.8, not the latest version (3.1.1).

Wow, took me forever to find that version. I had to download it & make it manually. Still didn't work, so I'm not sure what's going on there. 

> what distro are you compiling on and where are your openssl dev headers located?

Pop!_OS 22.04 LTS Kernel 6.2.6-76060206-generic
Not entirely sure what dev headers are, but as far as I know, openssl installed as it does by default, in usr/local/ssl. Although I have two other versions of it installed, not sure where those are exactly.

**Comment by GlennSchner** [comment]
Update, was looking at alternative solutions & I noticed that the repo this project was forked from talked about libssl-dev. Installing that seems to have fixed the issue. Can you leave a note somewhere to that effect?

**Comment by Neo-Desktop** [comment]
> Update, was looking at alternative solutions & I noticed that the repo this project was forked from talked about libssl-dev. Installing that seems to have fixed the issue. Can you leave a note somewhere to that effect?

That's a good idea, and  yes that's what I was talking about with the development headers earlier.

We'll mark this as closed for now
