### ISSUE TITLE
Isn't Microsoft mad from this repo or arent you afraid of Microsoft.

### ISSUE THREAD

**Issue by hemangjoshi37a** [Neo-Desktop/WindowsXPKg#7]
I hope that the owner of this repo know about the rules and regulations about intellectual property rights and takes consideration if anyone from Microsoft gets mad.

**Comment by TCB13** [comment]
Cmon this is Windows XP, even the source code of the OS is available here.

**Comment by Neo-Desktop** [comment]
Imagine white knighting for a billion dollar corporation.
